# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swipemoji' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swipemoji
	pod 'lottie-ios'

end

target 'SwipemojiKeyboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwipemojiKeyboard
	pod 'lottie-ios'

end
